on: [push]

jobs:
  review_job:
    runs-on: ubuntu-latest
    name: A job to validate the PR
    steps:
      - name: Invocation of testnet review action
        id: testnet-review-pr
        uses: parthdesai/action-testnet-review-pr
        with:
          requiredGenesisModification: true
          genTxDirectory: 1/2
          genesisFilePath: genesis.json
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
