# This is a basic workflow to help you get started with Actions

name: CI

on: 
  pull_request:
    branches:
      - main

jobs:
  review_job:
    runs-on: ubuntu-latest
    name: A job to validate the PR
    steps:
      - name: Invocation of testnet review action
        id: review
        uses: parthdesai/action-testnet-review-pr@5b14b726aaa0d23753102f82097182e0bfd83b82
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requiredGenesisModification: true
          genTxDirectory: 1/2
          genesisFilePath: genesis.json
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The output was ${{ steps.review.outputs }}"

